### ISSUE TITLE
How to disable imports sorting

### ISSUE THREAD

**Issue by sridattayalla** [purescript-emacs/purescript-mode#14]
I don't want to auto sort the imports when adding a new import. 
Please help me if there is any way I can do that.

**Comment by kritzcreek** [comment]
The import sorting happens as part of the automatic import insertion.

You can turn off import insertion on completion with `(setq psc-ide-add-import-on-completion nil)`.

**Comment by sridattayalla** [comment]
@kritzcreek thanks, It worked
