### ISSUE TITLE
Implement support for `ado`

### ISSUE THREAD

**Issue by reactormonk** [purescript-emacs/purescript-mode#2]
See https://github.com/purescript/purescript/pull/2889#issuecomment-301260299 for full specification. The easiest part may be the `ado` keyword, maybe there's more.

**Comment by purcell** [comment]
I presume you're talking about indentation support, in which case I believe this is working now, right?

**Comment by shaunplee** [comment]
I think I'm running into the same issue: `purescript-indentation-expression-list` and `purescript-indentation-peek-token` includes entries for `do` and `mdo` but not `ado`.

**Comment by shaunplee** [comment]
What *is* `mdo` anyway?

https://www.gocomics.com/calvinandhobbes/1992/05/01
