### ISSUE TITLE
Integration with `purty`

### ISSUE THREAD

**Issue by joneshf** [purescript-emacs/purescript-mode#5]
Howdy!

I maintain a source code formatter: [`purty`][purty]. I'd like to add support for [using it from emacs][integration].

Is this something that could be added to `purescript-mode`? If so, I'd like the burden on you to be as minimal as possible, so when the API of `purty` changes, I expect to update whatever's necessary to work here. Would it be easier if I maintained a `purty-mode` and `purescript-mode` depended on it somehow (I don't know enough about the emacs ecosystem). If it shouldn't be added to `purescript-mode`, no worries.

[integration]: https://gitlab.com/joneshf/purty/issues/123
[purty]: https://gitlab.com/joneshf/purty

**Comment by t61j** [comment]
Hi, any news on this? It would be really nice if purty integrated with purescript-mode already, even if it wouldn't have all the features wanted yet.
One of the worst things to me as beginner when writing purescript occurs when I need to edit jsx style nodes (react-basic for example). When I need to wrap some long snippet with another `div`, moving everything correctly again by hand is very so tedious). `purty` in those cases makes such a difference.
At the moment I use:
```
(use-package purescript-mode
  :ensure t
  :config
  (defun format-ps ()
    (interactive)
    (set-process-sentinel
     (start-process "auto-format-purescript"
                    (current-buffer)
                    "purty"
                    "--write"
                    buffer-file-name)
     (lambda (process event)
       (revert-buffer :ignore-auto :noconfirm))))
  :bind ("C-c C-f" . format-ps)
  :mode ("\\.purs$" . purescript-mode))
```

**Comment by kritzcreek** [comment]
Can you just use https://github.com/lassik/emacs-format-all-the-code? According to the README it knows how to invoke `purty` on PureScript code.

**Comment by t61j** [comment]
> Can you just use https://github.com/lassik/emacs-format-all-the-code? According to the README it knows how to invoke `purty` on PureScript code.

😅 Oh nice, I didn't know this package. Thanks

**Comment by purcell** [comment]
Another option: make a tiny `purty.el` package using [`reformatter`](https://github.com/purcell/emacs-reformatter) to easily get a `purty-format-on-save-mode` that you can enable.

Closing this ticket as out of scope for purescript-mode itself, though.
